version: '3.7'

services:
    database:
        image: postgres
        env_file:
            - ./config/database.env
        ports:
            - 5432:5432
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: always
    api:
        depends_on:
            - database
        build: ./api/
        restart: always
        env_file:
            - ./config/database.env
            - ./config/api.env
            - ./config/redis.env
        ports:
            - 5000:5000
        volumes:
            - "D:\\Wendel\\Programing\\Rest_APIs\\personal_projects\\flask_bank\\api:/app"
            
    redis:
        depends_on:
            - api
        image: redis
        ports:
            - 6379:6379
        restart: always
    pgadmin:
        depends_on:
            - database
        image: dpage/pgadmin4
        env_file:
            - ./config/pgadmin.env
        ports:
            - "5050:80"
        restart: always

volumes:
  db-data: